Repository Boutique-Cinema/boutique-cinema-springboot, pull requests merged in 2024-10, with the labels that each got.

#42 add : 도메인 member, 의존성추가, 비밀번호 암호화 기능추가(#30)
  build.gradle
  src/main/java/com/cinema/config/CustomSecurityConfig.java
  src/main/java/com/cinema/controller/MemberController.java
  src/main/java/com/cinema/domain/Member.java
  src/main/java/com/cinema/repository/MemberRepository.java
  src/main/java/com/cinema/service/MemberService.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
  src/main/resources/application.properties
Labels: add

#43 add : cors 추가(#30)
  src/main/java/com/cinema/config/CustomSecurityConfig.java
Labels: add

#44 add : member DTO추가 및 핸들러, 서블릿 추가(#30)
  src/main/java/com/cinema/config/CustomServletConfig.java
  src/main/java/com/cinema/controller/GlobalExceptionHandler.java
  src/main/java/com/cinema/dto/member/MemberJoinDTO.java
  src/main/java/com/cinema/dto/member/MemberModifyDTO.java
  src/test/java/com/cinema/repository/MemberRepositoryTest.java
Labels: add

#45 add, modify : 회원가입 페이지 기능추가(#30)
  src/main/java/com/cinema/controller/MemberController.java
  src/main/java/com/cinema/dto/member/MemberJoinDTO.java
  src/main/java/com/cinema/service/MemberService.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
Labels: add, modify

#50 modify : domain member의 변수명을 카멜형식으로 변경
  src/main/java/com/cinema/domain/Member.java
  src/main/java/com/cinema/dto/member/MemberJoinDTO.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
Labels: modify

#51 modify : domain member의 변수명을 카멜형식으로 변경(#30)
  src/main/java/com/cinema/domain/Member.java
Labels: modify

#52 create : 관리자 회원 List 생성, 회원 이름,id 검색 생성(#46)
  build.gradle
  src/main/java/com/cinema/controller/MemberController.java
  src/main/java/com/cinema/dto/member/AdminMemberListDTO.java
  src/main/java/com/cinema/repository/MemberRepository.java
  src/main/java/com/cinema/service/MemberService.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
  src/test/java/com/cinema/repository/MemberRepositoryTest.java
Labels: add

#59 feat : 영화 날짜 검색 기능 구현(#54)
  src/main/java/com/cinema/controller/MovieController.java
  src/main/java/com/cinema/repository/MovieRepository.java
  src/main/java/com/cinema/service/MovieService.java
  src/main/java/com/cinema/service/MovieServiceImpl.java
Labels: feat

#60 modify : 공지사항 api 연결 성공-진우님 대신 커밋(#58)
  src/main/java/com/cinema/controller/NoticeController.java
  src/main/java/com/cinema/domain/Notice.java
  src/main/java/com/cinema/service/NoticeService.java
  src/main/java/com/cinema/service/NoticeServiceImpl.java
Labels: add

#63 modify : 영화 이미지 썸네일 기능 구현, 상영관별 정렬 기능 삭제(#62)
  src/main/java/com/cinema/controller/MovieController.java
  src/main/java/com/cinema/dto/movie/MovieDTO.java
  src/main/java/com/cinema/repository/MovieRepository.java
  src/main/java/com/cinema/service/MovieService.java
  src/main/java/com/cinema/service/MovieServiceImpl.java
  src/main/java/com/cinema/util/CustomFileUtil.java
Labels: feat, modify

#67 add, modify : gson의존성 추가 및 CustomSecurityConfig.java 수정, 로그인 기능 추가
  build.gradle
  src/main/java/com/cinema/config/APILoginFailHandler.java
  src/main/java/com/cinema/config/APILoginSuccessHandler.java
  src/main/java/com/cinema/config/CustomSecurityConfig.java
  src/main/java/com/cinema/controller/MemberController.java
  src/main/java/com/cinema/domain/Member.java
  src/main/java/com/cinema/domain/MemberRole.java
  src/main/java/com/cinema/dto/member/MemberDTO.java
  src/main/java/com/cinema/dto/member/MemberJoinDTO.java
  src/main/java/com/cinema/repository/MemberRepository.java
  src/main/java/com/cinema/service/CustomUserDetailService.java
  src/main/java/com/cinema/service/MemberService.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
  src/test/java/com/cinema/repository/MemberRepositoryTest.java
Labels: add, modify

#68 add : spring-boot-starter-validation 의존성 추가
  build.gradle
Labels: add

#69 add : spring-boot-starter-validation 의존성 추가(gson)
  build.gradle
Labels: add

#72 modify : 공지사항 기능 수정 완료!!(#66)
  src/main/java/com/cinema/config/ModelMapperConfig.java
  src/main/java/com/cinema/controller/NoticeController.java
  src/main/java/com/cinema/repository/NoticeRepository.java
  src/main/java/com/cinema/service/NoticeService.java
  src/main/java/com/cinema/service/NoticeServiceImpl.java
Labels: modify

#73 feat : 사용자 1대1문의 질문 등록,수정,삭제,상세조회, 리스트, 페이지네이션 기능 구현(#64)
  src/main/java/com/cinema/controller/MovieController.java
  src/main/java/com/cinema/controller/QuestionController.java
  src/main/java/com/cinema/domain/Question.java
  src/main/java/com/cinema/dto/qna/QuestionDTO.java
  src/main/java/com/cinema/service/QuestionService.java
  src/test/java/com/cinema/repository/QuestionRepositoryTest.java
Labels: add, feat

#74 add, modify : JWT 토큰 인증구현을 위한 파일 추가 및 수정(#53)
  build.gradle
  package-lock.json
  src/main/java/com/cinema/config/APILoginSuccessHandler.java
  src/main/java/com/cinema/config/CustomSecurityConfig.java
  src/main/java/com/cinema/controller/MemberController.java
  src/main/java/com/cinema/security/filter/JWTCheckFilter.java
  src/main/java/com/cinema/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/cinema/util/CustomJWTException.java
  src/main/java/com/cinema/util/JWTUtil.java
Labels: add, modify

#75 예매api구현#31
  src/main/java/com/cinema/BoutiqueCinemaSpringbootApplication.java
  src/main/java/com/cinema/config/RootConfig.java
  src/main/java/com/cinema/controller/ReservationController.java
  src/main/java/com/cinema/domain/Reservation.java
  src/main/java/com/cinema/dto/reservation/ReservationDTO.java
  src/main/java/com/cinema/repository/ReservationRepository.java
  src/main/java/com/cinema/service/ReservationService.java
  src/main/java/com/cinema/service/ReservationServiceImpl.java
Labels: add, feat

#78 modify : 공지사항 기능수정 & 회원 관리 리스트 기능구현(#81)
  src/main/java/com/cinema/service/NoticeService.java
  src/main/java/com/cinema/service/NoticeServiceImpl.java
Labels: modify

#81 add : RefreshToken을 검증하는 컨트롤러, 토큰이 없을 때 처리할 컨트롤러 추가(#80)
  src/main/java/com/cinema/config/CustomSecurityConfig.java
  src/main/java/com/cinema/controller/APIRefreshController.java
  src/main/java/com/cinema/controller/advice/CustomControllerAdvice.java
  src/main/java/com/cinema/security/filter/JWTCheckFilter.java
Labels: add

#83 add, modify : 로그인 했을 때 모든값 불러오기 추가, 권한에 따른 접근설정(#80)
  src/main/java/com/cinema/config/CustomSecurityConfig.java
  src/main/java/com/cinema/controller/MovieController.java
  src/main/java/com/cinema/dto/member/MemberDTO.java
  src/main/java/com/cinema/security/filter/JWTCheckFilter.java
  src/main/java/com/cinema/service/CustomUserDetailService.java
Labels: add, modify

#84 modify : QuetionserviceImpl 수정(#64)
  src/main/java/com/cinema/config/RootConfig.java
  src/main/java/com/cinema/service/QuestionServiceImpl.java
  src/main/resources/application.properties
Labels: modify

#88 Feature#31
  src/main/java/com/cinema/controller/ReservationController.java
  src/main/java/com/cinema/domain/Reservation.java
  src/main/java/com/cinema/dto/reservation/ReservationDTO.java
  src/main/java/com/cinema/dto/reservation/ReviewDTO.java
  src/main/java/com/cinema/service/ReservationService.java
  src/main/java/com/cinema/service/ReservationServiceImpl.java
Labels: feat, modify

#90 modify : QuestionController 주석 해제(#89)
  src/main/java/com/cinema/controller/QuestionController.java
Labels: modify

#91 delete : PageDTO, sales관련 파일 삭제(#89)
  src/main/java/com/cinema/dto/common/PageRequestDTO.java
  src/main/java/com/cinema/dto/common/PageResponseDTO.java
  src/main/java/com/cinema/repository/SalesRepository.java
  src/main/java/com/cinema/service/SalesService.java
  src/main/java/com/cinema/service/SalesServiceImpl.java
Labels: delete

#92 modify : 토큰검사 안하는 url 수정(#80)
  src/main/java/com/cinema/security/filter/JWTCheckFilter.java
Labels: modify

#97 modify : JWTCheckFilter 경로수정, 오타수정
  src/main/java/com/cinema/dto/member/MemberDTO.java
  src/main/java/com/cinema/security/filter/JWTCheckFilter.java
Labels: modify

#98 modify : CustomSecurityConfig 코드 수정
  src/main/java/com/cinema/config/CustomSecurityConfig.java
Labels: modify

#100 add : 회원관리 특정검색 기능추가
  src/main/java/com/cinema/controller/MemberController.java
  src/main/java/com/cinema/service/MemberService.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
Labels: add

#107 modify : movie,question의 DTO 수정
  src/main/java/com/cinema/controller/QuestionController.java
  src/main/java/com/cinema/domain/Movie.java
  src/main/java/com/cinema/dto/movie/MovieDTO.java
  src/main/java/com/cinema/dto/qna/QuestionDTO.java
Labels: modify

#102 add, modify : 아이디 비밀번호찾기 기능추가(#80)
  src/main/java/com/cinema/controller/MemberController.java
  src/main/java/com/cinema/dto/member/CheckToResetPasswordDTO.java
  src/main/java/com/cinema/dto/member/FindIdDTO.java
  src/main/java/com/cinema/dto/member/ResetPasswordDTO.java
  src/main/java/com/cinema/repository/MemberRepository.java
  src/main/java/com/cinema/security/filter/JWTCheckFilter.java
  src/main/java/com/cinema/service/MemberService.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
Labels: add, modify

#110 modify : JWT 공지사항 수정
  src/main/java/com/cinema/controller/NoticeController.java
  src/main/java/com/cinema/security/filter/JWTCheckFilter.java
Labels: modify

#112 feat : 파이썬 이미지 객체 탐지 api 연결(#108)
  build.gradle
  src/main/java/com/cinema/config/WebClientConfig.java
  src/main/java/com/cinema/controller/python/ReqController.java
Labels: feat

#114 modify : 공지사항 등록일 순이 아니라 번호순으로 내림차순 수정
  src/main/java/com/cinema/repository/NoticeRepository.java
Labels: modify
