Repository Boutique-Cinema/boutique-cinema-springboot, pull requests merged in 2024-09, with the labels that each got.

#5 create : 레포지토리 기본틀 생성(#18)
  src/main/java/com/cinema/repository/AnswerRepository.java
  src/main/java/com/cinema/repository/MemberRepository.java
  src/main/java/com/cinema/repository/MovieRepository.java
  src/main/java/com/cinema/repository/NoticeRepository.java
  src/main/java/com/cinema/repository/QuestionRepository.java
  src/main/java/com/cinema/repository/ReservationRepository.java
  src/main/java/com/cinema/repository/SalesRepository.java
Labels: add

#8 create : 도메인 기본틀 생성(#20)
  src/main/java/com/cinema/domain/Answer.java
  src/main/java/com/cinema/domain/Member.java
  src/main/java/com/cinema/domain/Movie.java
  src/main/java/com/cinema/domain/Notice.java
  src/main/java/com/cinema/domain/Question.java
  src/main/java/com/cinema/domain/Reservation.java
Labels: add, modify

#13 add : domain(Reservation) 기본틀 생성
  src/main/java/com/cinema/domain/Reservation.java
Labels: add, modify

#9 add : 서비스 기본틀 생성#19
  src/main/java/com/cinema/service/AnswerService.java
  src/main/java/com/cinema/service/AnswerServiceImpl.java
  src/main/java/com/cinema/service/NoticeService.java
  src/main/java/com/cinema/service/NoticeServiceImpl.java
  src/main/java/com/cinema/service/QuestionService.java
  src/main/java/com/cinema/service/QuestionServiceImpl.java
  src/main/java/com/cinema/service/SalesService.java
  src/main/java/com/cinema/service/SalesServiceImpl.java
Labels: add

#14 add : 영화(Movie), 회원(Member) 서비스 생성(#11)
  src/main/java/com/cinema/service/MemberService.java
  src/main/java/com/cinema/service/MemberServiceImpl.java
  src/main/java/com/cinema/service/MovieService.java
  src/main/java/com/cinema/service/MovieServiceImpl.java
  src/main/resources/application.properties
Labels: add

#17 시큐리티 기본틀 생성(#15)
  src/main/java/com/cinema/security/CustomUserDetailService.java
  src/main/java/com/cinema/security/handler/APILoginFailHandler.java
  src/main/java/com/cinema/security/handler/APILoginSuccessHandler.java
  src/main/java/com/cinema/security/handler/CustomAccessDeniedHandler.java
Labels: add

#23 유틸 기본틀 생성(#21)
  src/main/java/com/cinema/util/CustomFileUtil.java
  src/main/java/com/cinema/util/CustomJWTException.java
Labels: add

#26 add, modfiy : 회원, 1:1문의 엔티티, 레포지토리 생성
  src/main/java/com/cinema/domain/Member.java
  src/main/java/com/cinema/domain/Question.java
  src/main/java/com/cinema/repository/AnswerRepository.java
  src/main/java/com/cinema/repository/MemberRepository.java
  src/main/java/com/cinema/repository/MovieRepository.java
  src/main/java/com/cinema/repository/NoticeRepository.java
  src/main/java/com/cinema/repository/QuestionRepository.java
  src/main/java/com/cinema/repository/SalesRepository.java
  src/main/resources/application.properties
Labels: add, modify

#28 modify : Movie 클래스의 roundTime에 nullable = false 추가, Test파일에 주석 제거
  src/main/java/com/cinema/domain/Movie.java
  src/test/java/com/cinema/repository/MovieRepositoryTest.java
  src/test/java/com/cinema/service/MovieServiceTest.java
Labels: modify

#32 feat : 영화 수정,삭제 기능 구현(#29)
  src/main/java/com/cinema/controller/MovieController.java
  src/main/java/com/cinema/domain/Movie.java
  src/main/java/com/cinema/service/MovieServiceImpl.java
  src/test/java/com/cinema/repository/MovieRepositoryTest.java
  src/test/java/com/cinema/service/MovieServiceTest.java
Labels: feat

#34 feat : 영화 페이지네이션, 상세페이지, 리스트, 제목으로 검색하는 기능 구현(#33)
  src/main/java/com/cinema/controller/MovieController.java
  src/main/java/com/cinema/domain/Movie.java
  src/main/java/com/cinema/dto/movie/MovieDTO.java
  src/main/java/com/cinema/repository/MovieRepository.java
  src/main/java/com/cinema/service/MovieService.java
  src/main/java/com/cinema/service/MovieServiceImpl.java
  src/test/java/com/cinema/repository/MovieRepositoryTest.java
Labels: feat

#38 modify : MovieService에 @Service 애너테이션 추가(#35)
  src/main/java/com/cinema/service/MovieService.java
Labels: modify
